name: Connected
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bottom_navy_bar: ^5.4.0
  line_awesome_flutter: ^1.0.1
  google_fonts: ^1.1.0
  store_redirect: ^1.0.2
  ff_navigation_bar: ^0.1.5
  titled_navigation_bar: ^4.1.0
  cloud_firestore: ^0.13.7
  firebase_auth: ^0.16.1
  file_picker: ^1.13.0+1
  firebase_storage: ^3.1.6
  uuid: ^2.2.0
  google_sign_in: ^4.5.1
  dynamic_theme: ^1.0.0
  flutter_phoenix: "^0.1.0"
  # page_transition: ^1.1.6

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
